### ISSUE TITLE
usage and license

### ISSUE THREAD

**Issue by frispete** [takluyver/distutils_symlink#1]
Dear Thomas,

I'm looking for a custom install_scripts method, that creates symlinks in /usr/{bin,sbin} to the real destination, and your distutils_symlink module is getting pretty close. 

Being a distutils/setuptools illiterate, I've no idea, how to integrate your module into my setup.py. Do you have an usage example, you can point me to?

While at it, there no license assigned, hence I'm not sure, if I'm allowed to use it..

Thanks,
Pete

**Comment by takluyver** [comment]
Hi @frispete - apologies, it was something I never really finished making reusable. I think, looking at the code, you use it like this:

``` python
from distutils_symlink import cmdclasses

setup(...,
      cmdclass=cmdclasses
     )
```

And then run `setup.py symlink` to create a symlink.

I'd consider this MIT licensed. I'll stick a LICENSE file in there.
